### ISSUE TITLE
  Undefined constant "AF_INET"

### ISSUE THREAD

**Issue by victorlbs** [atom-retros/atomcms#191]
In habbo.php line 29:

Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In habbo.php line 29:

  Undefined constant "AF_INET"

how can it be resolved?

**Comment by DennisObject** [comment]
@victorlbs Please refer the README or [retro](https://retros.guide/docs/category/atom-cms)
