### ISSUE TITLE
Unable to locate file in Vite manifest: resources/themes/atom/css/app.scss.

### ISSUE THREAD

**Issue by ERRORESES** [atom-retros/atomcms#202]
PHP 8.3.9
11.0.7

I've tried with PHP 8.3.1 and the same.
if i put debug mode in false only shows me a 500 ERROR.
When i've change to TRUE shows me this:

Unable to locate file in Vite manifest: resources/themes/atom/css/app.scss.

C:\inetpub\wwwroot\atomcms\resources\themes\atom\views\layouts\app.blade
.php
 
: 22
require

    @vite(['resources/themes/' .  setting('theme') . '/css/app.scss', 'resources/themes/' .  setting('theme') . '/js/app.js'], 'build')

I've a Windows VPS with 16gbs ram and 4vcpu
Tried with windows10 & windows server 2022 the latest times and always showing me this issue.
Im using the latest version of the project.
The website works properly during the installation, after that no.

**Comment by DennisObject** [comment]
Fixed
